- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: Add repository
  ansible.builtin.yum_repository:
    name: jenkins
    baseurl: https://pkg.jenkins.io/redhat-stable/jenkins.repo

- name: install "{{ dnf_modules }}"
  ansible.builtin.import_role:
    name: dnf-module
    tasks_from: main.yml